### User defined functions
1) own module creation and usage <br>
2) python advanced packages intro
* numpy
* pandas
* matplotlib 

### 1)    own module creation and usage

#### ***   If program is not running restart the Kernel **********

In [ ]:
import functions
functions.pi

In [ ]:
functions.name

In [ ]:
dir(functions)

In [ ]:
import functions as f
f.name

In [ ]:
dir(f)

In [ ]:
f.sqrt

In [ ]:
f.sqrt

In [ ]:
import functions
help(functions.welcome)

In [ ]:
help(functions.sqrt)

In [ ]:
def welcome(name):
    ''' it will print the name with welcome'''
    print("Welcome "+name)
help(welcome)

In [ ]:
functions.sqrt(9)

In [ ]:
functions.sqrt(25)

In [ ]:
import fun
fun.square(5)

In [ ]:
fun.power(5,3)

In [ ]:
import fun

In [ ]:
import fun
fun.multiply(5,2)

In [ ]:
fun.power(5,5)

In [ ]:
fun.power(5,3)

In [ ]:
fun.power(5,4)

In [ ]:
fun.multiply(10,30)

In [ ]:
import math_type

In [ ]:
math_type.square(3)

In [ ]:
help(math)

In [ ]:
math_type.addition(19,1)

In [ ]:
math_type.subtraction(10,20)

In [ ]:
# package numpy
import numpy


In [ ]:
import numpy as np
a = np.array([34,56,99])
print(type(a))

In [ ]:
print(a.ndim)
print(a.shape)   # returns tuple
print(a.size)
print(a.itemsize)
print(a.dtype)

In [ ]:
import numpy as np
b = np.array([[34,56,99],[22,10,33]])
print(type(b))

In [ ]:
print(b.ndim,'   dimension')
print(b.shape,'   martix size') 
print(b.size, '   number of elements')
print(b.itemsize,'   bytes required')
print(b.dtype,'    data type')

In [ ]:
import numpy as np
a = np.array([34,56,99],dtype=np.int8)
print(a.itemsize)
print(a.dtype)

In [ ]:
import numpy as np
a = np.array([34,56,99],dtype=np.int16)
print(a.itemsize)
print(a.dtype)

In [ ]:
import numpy as np
a = np.array([34,56,99],dtype=np.int64)
print(a.itemsize)
print(a.dtype)

In [ ]:
L = [45,78,89,77,90]
# o/p = adding each element in the list
M = L+5 ## does not work

In [ ]:
L = [45,78,89,77,90]
# o/p = adding 5 each element in the list
# it can be done using for loop or
# by using lambda and map modules


In [ ]:
L = [45,78,89,77,90]
print(L)
for i in range(len(L)):
    L[i] = L[i]+5
    print(L, 'loop-',i)

In [ ]:
L = [45,78,89,77,90]
print(L)
L = list(map(lambda x:x+5,L))
print(L)

In [ ]:
L = [45,78,89,77,90]
print(L)
L = np.array(L)
print(L)
print(type(L))
print(L+5)

In [ ]:
L1 = [1,2,3,4,5]
L2 = [10,9,8,7,6]
L1 = np.array(L1)
L2 = np.array(L2)
print(L1)
print(L2)
print(L1+L2)
print(L1*L2)

In [5]:
import numpy as np
import time
values = list(range(1000000))
s = time.time()
lvalues = [i**2 for i in values]
e = time.time()
print(e-s)
#print(lvalues)
## same can be done using
s = time.time()
avalues = np.array(values)
asvalues = avalues**2
e = time.time()
print(e-s)
#print(asvalues)

0.36690187454223633
0.053168296813964844


In [14]:
import numpy as np
ap = np.arange(10,55,5) # step of 5 increments and stops at 50
print(ap)
ar = np.linspace(10,55,5) # spilts in to 5 equal 
print(ar)

[10 15 20 25 30 35 40 45 50]
[10.   21.25 32.5  43.75 55.  ]


#### other functions to create numpy arrays
- numpy.ones
- numpy.zeros
- numpy.full
- numpy.eye
- numpy.diag
###### random package
- numpy.random
- numpy.linalg

In [16]:
import numpy
help(numpy)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [17]:
numpy.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [18]:
numpy.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [19]:
numpy.arange(100).reshape(10,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]],

       [[50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64],
        [65, 66, 67, 68, 69]],

       [[70, 71, 72, 73, 74],
        [75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84],
        [85, 86, 87, 88, 89]],

       [[90, 91, 92, 93, 94],
        [95, 96, 97, 98, 99]]])

## Pandas

In [21]:
import pandas as pd
df = pd.read_csv("marks.csv") #for comma separated version
# pd.read_tsv("") for tab separated version
# pd.read_xlx("") for excel file
df

name  marks  rollno
0  rajesh     77       1
1  murari     89       2
2   angel     99       3
3  joshua     98       4

In [22]:
type(df)

pandas.core.frame.DataFrame

In [23]:
df.shape

(4, 3)

In [24]:
df['name']

0    rajesh
1    murari
2     angel
3    joshua
Name: name, dtype: object

In [27]:
df['marks']

0    77
1    89
2    99
3    98
Name: marks, dtype: int64

In [33]:
df['marks'].mean()

90.75

In [35]:
df['marks'].median()

93.5

In [36]:
pd.__version__

'0.24.2'

In [37]:
np.__version__

'1.16.2'